config/routes.rb
Rails.application.routes.draw do
  resources :pets
  resources :owners
  resources :veterinarians
  root to: 'veterinarians#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owner.rb
class Owner < ActiveRecord::Base
    belongs_to :veterinarian
    has_many :pets
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  ANIMAL_LIST = [:dog, :cat, :other]
  enum animal: ANIMAL_LIST
  belongs_to :owners
end

app/models/veterinarian.rb
class Veterinarian < ActiveRecord::Base
    has_many :owners
    has_many :pets, through: :owners
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name, :phone, :veterinarian_id)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :chip, :animal, :owner_id)
    end
end

app/controllers/veterinarians_controller.rb
class VeterinariansController < ApplicationController
  before_action :set_veterinarian, only: [:show, :edit, :update, :destroy]

  # GET /veterinarians
  # GET /veterinarians.json
  def index
    @veterinarians = Veterinarian.all
  end

  # GET /veterinarians/1
  # GET /veterinarians/1.json
  def show
  end

  # GET /veterinarians/new
  def new
    @veterinarian = Veterinarian.new
  end

  # GET /veterinarians/1/edit
  def edit
  end

  # POST /veterinarians
  # POST /veterinarians.json
  def create
    @veterinarian = Veterinarian.new(veterinarian_params)

    respond_to do |format|
      if @veterinarian.save
        format.html { redirect_to @veterinarian, notice: 'Veterinarian was successfully created.' }
        format.json { render :show, status: :created, location: @veterinarian }
      else
        format.html { render :new }
        format.json { render json: @veterinarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veterinarians/1
  # PATCH/PUT /veterinarians/1.json
  def update
    respond_to do |format|
      if @veterinarian.update(veterinarian_params)
        format.html { redirect_to @veterinarian, notice: 'Veterinarian was successfully updated.' }
        format.json { render :show, status: :ok, location: @veterinarian }
      else
        format.html { render :edit }
        format.json { render json: @veterinarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veterinarians/1
  # DELETE /veterinarians/1.json
  def destroy
    @veterinarian.destroy
    respond_to do |format|
      format.html { redirect_to veterinarians_url, notice: 'Veterinarian was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veterinarian
      @veterinarian = Veterinarian.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def veterinarian_params
      params.require(:veterinarian).permit(:name, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Fixed navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if current_page?('/') || current_page?('/veterinarians') %>"><%= link_to 'Doctors', veterinarians_path, class: 'nav-link' %></li>
      <li class="nav-item <%= 'active' if current_page?('/owners') %>"><%= link_to 'Owners', owners_path, class: 'nav-link' %></li>
      <li class="nav-item <%= 'active' if current_page?('/pets') %>"><%= link_to 'Pets', pets_path, class: 'nav-link' %></li>
    </ul>
    <%= yield :navigation %>
  </div>
</nav>

app/views/layouts/_search.html.erb
<!--
  Hint: You will probably want to submit a full form instead of using the
        following text field. What other fields are necessary to perform
        the search, and to where should the form be submitted?
 -->

<form class="form-inline mt-2 mt-md-0">
  <%= text_field_tag 'search', nil, class: 'form-control mr-sm-2', placeholder: 'Search pets...' %>
  <!-- this button should not be necessary -->
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeExercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div id='container' class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :veterinarian_id %><br>
    <%= f.number_field :veterinarian_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Owners</h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Veterinarian</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.name %></td>
        <td><%= owner.phone %></td>
        <td><%= owner.veterinarian_id %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path, class: 'btn btn-success' %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @owner.name %> <small>Owner</small></h2>

<p>
  <strong>Phone:</strong>
  <%= @owner.phone %>
</p>

<p>
  <strong>Veterinarian:</strong>
  <%= @owner.veterinarian_id %>
</p>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :chip %><br>
    <%= f.text_field :chip %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.number_field :owner_id %>
  </div>
  <div class="field">
    <%= f.label :animal %><br>
    <%= f.select :animal, Pet::ANIMAL_LIST %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pets</h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Chip</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.animal %></td>
        <td><%= pet.chip %></td>
        <td><%= pet.owner_id %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path, class: 'btn btn-success' %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @pet.name %> <small>Pet</small></h2>

<p>
  <strong>Chip:</strong>
  <%= @pet.chip %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @pet.owner_id %>
</p>

<p>
  <strong>Animal:</strong>
  <%= @pet.animal %>
</p>

app/views/veterinarians/_form.html.erb
<%= form_for(@veterinarian) do |f| %>
  <% if @veterinarian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@veterinarian.errors.count, "error") %> prohibited this veterinarian from being saved:</h2>

      <ul>
      <% @veterinarian.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/veterinarians/edit.html.erb
<h1>Editing Veterinarian</h1>

<%= render 'form' %>

<%= link_to 'Show', @veterinarian %> |
<%= link_to 'Back', veterinarians_path %>

app/views/veterinarians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Veterinarians</h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Client/Owners</th>
      <th>Cats</th>
      <th>Dogs</th>
      <th>Other</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @veterinarians.each do |veterinarian| %>
      <tr>
        <td><%= veterinarian.name %></td>
        <td><%= veterinarian.phone %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= link_to 'Show', veterinarian %></td>
        <td><%= link_to 'Edit', edit_veterinarian_path(veterinarian) %></td>
        <td><%= link_to 'Destroy', veterinarian, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Veterinarian', new_veterinarian_path, class: 'btn btn-success' %>

app/views/veterinarians/new.html.erb
<h1>New Veterinarian</h1>

<%= render 'form' %>

<%= link_to 'Back', veterinarians_path %>

app/views/veterinarians/show.html.erb
<% content_for :navigation do %>
  <%= render 'layouts/search' %>
<% end %>

<p id="notice"><%= notice %></p>

<h2><%= @veterinarian.name %> <small>Veterinarian</small></h2>

<p>
  <strong>Phone:</strong>
  <%= @veterinarian.phone %>
</p>

<h3>Search Results</h3>
<p id='no-results'>No results...</p>
<ul id='search_results'>
  <!--
    Search results go here
  -->
</ul>